#!/bin/bash

#Layout credit to github.com/stephen304/dotfiles

function gitt_help(){
  echo "Usage: gitt <subcommand> [arguments]"
  echo "Subcommands:"
  echo "    shove [commit message] "
  echo "    - Adds all changes, commits, pulls, and pushes"
  echo "    update <directory> "
  echo "    - updates a directory's repository"
  echo ""
}

function printusage(){
  gitt_${subcommand}_help
  echo ""
}

function gitt_renew_help(){
  echo "USAGE: renew <directory> "
  echo "    - silently pulls a directory's repository"
}

function gitt_renew(){
  if [ $# -eq 1 ]
  then
    cd $1
    git pull > /dev/null > /dev/null &
    exit 0
  else
    echo "ERROR: Bad arguments"
    printusage
    exit 1
  fi
}

function gitt_shove_help(){
  echo "USAGE: gitt shove [commit message]"
  echo "- Adds all changes, commits, pulls, and pushes"
  echo "- if no commit message is supplied 'updated' will be used"
}

function gitt_shove(){
  MESSAGE=$1
  if [ $# -lt 1 ]; then
    MESSAGE="updated"
  fi
  if [ $# -gt 1 ]; then
    echo "ERROR: Too many arguments"
    printusage
    exit 1
  fi
  git pull
  find . -name .DS_Store -print0 | xargs -0 rm -f --
  git add --all .
  git commit -m "$MESSAGE"
  git push
  echo "------------"
  echo "Commit ID: "
  git rev-parse HEAD
  echo "-------------"
  time=$(date +"%r")
  echo "Current time: $time"
  git add .
  git commit
}

function swapaliases(){
  subcommand=$1
  case $1 in
    "" | "-h" | "--help")
    subcommand="help"
    ;;
    "s")
    subcommand="shove"
    ;;
  esac
}

swapaliases $1
case $2 in
  "-h" | "--help")
  printusage
  exit 0
  ;;
esac
case $subcommand in
  "" | "-h" | "--help")
  gitt_help
  exit 0
  ;;
  *)
  shift
  gitt_${subcommand} $@
  if [ $? = 127 ]; then
    echo "Error: '$subcommand' is not a known subcommand." >&2
    echo "       Run '$progname --help' for a list of known subcommands." >&2
    exit 1
  fi
  ;;
esac
