#!/bin/bash

if [ $# -eq 0 ]
then
  ~/.bin/.subl
elif [ $# -eq 1 ]
then
  if [ -f $1 ]
  then
    ~/.bin/.subl $1
  elif [ -d $1 ]
    then
    echo "$1 is a directory"
    echo "Usage: subl [filename]"
  else
    echo "$1 does not exist"
    echo "Usage: subl [filename]"
  fi
else
  echo "ERROR: Failed to open Sublime. Too many arguments"
  echo "USAGE: subl [filename]"
  exit 1 # terminate and indicate error
fi
